### ISSUE TITLE
Disable resize pic for books preview

### ISSUE THREAD

**Issue by IgorPolyakov** [IgorPolyakov/what-did-i-read#5]
![image](https://user-images.githubusercontent.com/2613581/39687049-add222f8-51f6-11e8-8300-99a3fd9deecc.png)

**Comment by AlexBazh** [comment]
Fixed
https://github.com/IgorPolyakov/what-did-i-read/commit/b8bc7b74c35ee8e31a8a19b9c4d6dde1c8013099
